name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  code_text_field: ^1.1.0
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  json_to_dto: 
    path: ../
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  
