
include: package:austerity/analysis_options.yaml

lints:
  - avoid_annotating_with_dynamic: false

analyzer:
  errors:
    avoid_annotating_with_dynamic: ignore
    implicit_dynamic_method: ignore
    lines_longer_than_80_chars: ignore
    public_member_api_docs: error

  exclude:
    - 'test/person.dart'
    - 'test/book.dart'