name: json_to_dto
description: Convert JSON to Dart DTOs and back. Automate the model creation and the toJson and fromJson methods
version: 0.1.0-beta
repository: https://github.com/MelbourneDeveloper/json_to_dto

environment:
  sdk: '>=2.19.4 <3.0.0'


dev_dependencies:
  austerity: ^0.0.10-beta
  lints: ^2.0.0
  test: ^1.21.0
